from __future__ import annotations

from pathlib import Path

from .assigner import AssignedStructure
from .params import ClayFFParameters


PREFERRED_ATOM_TYPE_ORDER = (
    "st",
    "ob",
    "obss",
    "ao",
    "oh",
    "obos",
    "at",
    "obts",
    "mgo",
    "ohs",
    "ho",
    "o*",
    "h*",
    "Na",
    "K",
    "Cs",
    "Ca",
    "Ba",
    "Mg",
    "Sr",
    "Pb",
    "Cl",
)

PREFERRED_BOND_ORDER = ("oh-ho", "ohs-ho", "o*-h*")
PREFERRED_ANGLE_ORDER = ("h*-o*-h*",)


def _ordered_types(used: set[str], preferred: tuple[str, ...], fallback: tuple[str, ...]) -> list[str]:
    ordered = [atom_type for atom_type in preferred if atom_type in used]
    ordered.extend(atom_type for atom_type in fallback if atom_type in used and atom_type not in ordered)
    ordered.extend(sorted(used - set(ordered)))
    return ordered


def write_lammps_data(
    assigned: AssignedStructure,
    forcefield: ClayFFParameters,
    output_path: str | Path,
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    used_atom_types = {atom.ff_type for atom in assigned.atoms}
    atom_type_order = _ordered_types(
        used_atom_types,
        PREFERRED_ATOM_TYPE_ORDER,
        forcefield.atom_type_order,
    )
    atom_type_ids = {atom_type: index + 1 for index, atom_type in enumerate(atom_type_order)}

    used_bond_types = {bond.bond_type for bond in assigned.bonds}
    bond_type_order = _ordered_types(used_bond_types, PREFERRED_BOND_ORDER, ())
    bond_type_ids = {bond_type: index + 1 for index, bond_type in enumerate(bond_type_order)}

    used_angle_types = {angle.angle_type for angle in assigned.angles}
    angle_type_order = _ordered_types(used_angle_types, PREFERRED_ANGLE_ORDER, ())
    angle_type_ids = {angle_type: index + 1 for index, angle_type in enumerate(angle_type_order)}

    xlo, xhi, ylo, yhi, zlo, zhi, xy, xz, yz = assigned.cell.cell.triclinic_box()

    lines: list[str] = []
    lines.append(
        f"LAMMPS data file generated by assign_clayff.py for {assigned.title}"
    )
    lines.append("")
    lines.append(f"{len(assigned.atoms):6d} atoms")
    lines.append(f"{len(assigned.bonds):6d} bonds")
    lines.append(f"{len(assigned.angles):6d} angles")
    lines.append(f"{0:6d} dihedrals")
    lines.append(f"{0:6d} impropers")
    lines.append("")
    lines.append(f"{len(atom_type_order):6d} atom types")
    if bond_type_order:
        lines.append(f"{len(bond_type_order):6d} bond types")
    if angle_type_order:
        lines.append(f"{len(angle_type_order):6d} angle types")
    lines.append("")
    lines.append(f"{xlo:15.9f} {xhi:15.9f} xlo xhi")
    lines.append(f"{ylo:15.9f} {yhi:15.9f} ylo yhi")
    lines.append(f"{zlo:15.9f} {zhi:15.9f} zlo zhi")
    lines.append(f"{xy:15.9f} {xz:15.9f} {yz:15.9f} xy xz yz")
    lines.append("")

    lines.append("Masses")
    lines.append("")
    for atom_type in atom_type_order:
        parameter = forcefield.require_atom_type(atom_type)
        lines.append(
            f"{atom_type_ids[atom_type]:4d} {parameter.mass:10.6f} # {atom_type}"
        )
    lines.append("")

    lines.append("Pair Coeffs # lj/cut/coul/long")
    lines.append("")
    for atom_type in atom_type_order:
        parameter = forcefield.require_atom_type(atom_type)
        lines.append(
            f"{atom_type_ids[atom_type]:4d} {parameter.epsilon:13.10f} {parameter.sigma:13.10f} # {atom_type}"
        )
    lines.append("")

    if bond_type_order:
        lines.append("Bond Coeffs # harmonic")
        lines.append("")
        for bond_type in bond_type_order:
            atom_type_a, atom_type_b = bond_type.split("-")
            parameter = forcefield.get_bond(atom_type_a, atom_type_b)
            lines.append(
                f"{bond_type_ids[bond_type]:4d} {parameter.k2:10.4f} {parameter.r0:10.4f} # {bond_type}"
            )
        lines.append("")

    if angle_type_order:
        lines.append("Angle Coeffs # harmonic")
        lines.append("")
        for angle_type in angle_type_order:
            atom_type_a, atom_type_b, atom_type_c = angle_type.split("-")
            parameter = forcefield.get_angle(atom_type_a, atom_type_b, atom_type_c)
            lines.append(
                f"{angle_type_ids[angle_type]:4d} {parameter.k2:10.4f} {parameter.theta0:10.4f} # {angle_type}"
            )
        lines.append("")

    lines.append("Atoms # full")
    lines.append("")
    for atom in assigned.atoms:
        x_coord, y_coord, z_coord = assigned.cell.cell.frac_to_cart(atom.output_frac)
        lines.append(
            f"{atom.index:7d} {1:6d} {atom_type_ids[atom.ff_type]:3d} {atom.charge:9.6f} "
            f"{x_coord:15.9f} {y_coord:15.9f} {z_coord:15.9f} # {atom.ff_type}"
        )
    lines.append("")

    if assigned.bonds:
        lines.append("Bonds")
        lines.append("")
        for bond in assigned.bonds:
            lines.append(
                f"{bond.index:7d} {bond_type_ids[bond.bond_type]:3d} {bond.atom1_id:7d} {bond.atom2_id:7d}"
            )
        lines.append("")

    if assigned.angles:
        lines.append("Angles")
        lines.append("")
        for angle in assigned.angles:
            lines.append(
                f"{angle.index:7d} {angle_type_ids[angle.angle_type]:3d} {angle.atom1_id:7d} {angle.atom2_id:7d} {angle.atom3_id:7d}"
            )
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
